Network:
  seed: 1
  batch_size: 10
  lr: 3e-4
  weight_decay: 0
  amsgrad: True
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/MIMIC/
target_dir: /home/soroosh/Documents/Repositories_target_files/chestx/central/
network_save_freq: 1
display_stats_freq: 10
network_checkpoint_freq: 1
num_iterations: 1000