Network:
  batch_size: 5
  lr: 5e-5
  weight_decay: 0
  amsgrad: False
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/XRay/
target_dir: /home/soroosh/Documents/Repositories_target_files/chestx/
network_save_freq: 10 # number of epochs to save
display_stats_freq: 1 # valid freq is equal to this
num_epochs: 1000
num_epochs_single_head: 50

Network_single_head:
  batch_size: 5
  lr: 9e-5
  weight_decay: 0
  amsgrad: False
  tb_logs_path: tensor_board_logs/
  display_stats_freq: 1 # valid freq is equal to this
  network_output_path: network_data/
  output_data_path: output_data/
  stat_log_path: stat_logs
  network_save_freq: 5 # number of epochs to save
  trained_model_name: trained_model.pth