Network:
  batch_size: 8
  lr: 5e-5
  weight_decay: 0
  amsgrad: False
  num_epochs: 1000
  num_epochs_single_head: 10000
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /PATH TO DATASET/
target_dir: /WHERE YOU WANT TO STORE YOUR EXPERIMENTS/
display_stats_freq: 5 # valid freq is equal to this

Network_single_head:
  batch_size: 12
  lr: 9e-5
  weight_decay: 0
  amsgrad: False
  tb_logs_path: tensor_board_logs/
  display_stats_freq: 5 # valid freq is equal to this
  network_output_path: network_data/
  output_data_path: output_data/
  stat_log_path: stat_logs
  trained_model_name: trained_model.pth