Network:
  batch_size: 15
  lr: 5e-5
  weight_decay: 0
  amsgrad: False
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth
#label_names: ['atelectasis', 'cardiomegaly', 'consolidation', 'edema', 'enlarged_cardiomediastinum', 'fracture',
#              'lung_lesion', 'lung_opacity', 'no_finding', 'pleural_effusion', 'pleural_other', 'pneumonia',
#              'pneumothorax', 'support_devices']
label_names: ['poly_wafer', 'crack', 'inactive']

# changeable items:
#file_path: /home/soroosh/Documents/datasets/MIMIC/
file_path: /home/soroosh/Documents/datasets/solar_cells/
target_dir: /home/soroosh/Documents/Repositories_target_files/chestx/central/
network_save_freq: 500 # based on the batch size, shows the number of batches done
display_stats_freq: 50 # valid freq is also the same as this
display_train_loss_freq: 50
network_checkpoint_freq: 1
num_epochs: 1000